### ISSUE TITLE
Identify problem topic

### ISSUE THREAD

**Issue by alkindiisda** [alkindiisda/bangkityog3#1]
Find what problem need to be done using machine learning

**Comment by bayuprasetyaa** [comment]
Hello guys,
I'm trying to find several topik and datasets in kaggle. 

https://www.kaggle.com/balaka18/email-spam-classification-dataset-csv

The data talking about characteristic of spam email.
The description :
The csv file contains 5172 rows, each row for each email. There are 3002 columns. The first column indicates Email name. The name has been set with numbers and not recipients' name to protect privacy. The last column has the labels for prediction : 1 for spam, 0 for not spam. The remaining 3000 columns are the 3000 most common words in all the emails, after excluding the non-alphabetical characters/words. For each row, the count of each word(column) in that email(row) is stored in the respective cells. Thus, information regarding all 5172 emails are stored in a compact dataframe rather than as separate text files. 

I think we can make ML for learning from the data to classify spam email.
The advantage of this topic is that it might be a little bit easier than others.
but for the weakness of this topic is this topik maybe too mainstream.
What do you think?

**Comment by alkindiisda** [comment]
@bayuprasetyaa we will choose that topic to learn

**Comment by ilhamtohari** [comment]
I do agree with u. Sorry for not getting back to you sooner, guys.
